version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: telconova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1
    networks:
      - devcontainer-network

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - devcontainer-network

volumes:
  postgres-data:
    name: devcontainer_postgres_data

networks:
  devcontainer-network:
    driver: bridge