name: Build and Push to ECR

on:
  push:
    branches: [ main, develop, featere/aws-registry ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a2c8l1h5

    - name: Build Docker image
      run: |
        docker build -t public.ecr.aws/a2c8l1h5/workorder-service-so:${{ github.sha }} .
        docker tag public.ecr.aws/a2c8l1h5/workorder-service-so:${{ github.sha }} public.ecr.aws/a2c8l1h5/workorder-service-so:latest

    - name: Push Docker image
      run: |
        docker push public.ecr.aws/a2c8l1h5/workorder-service-so:${{ github.sha }}
        docker push public.ecr.aws/a2c8l1h5/workorder-service-so:latest

    - name: Output image details
      run: |
        echo "Image pushed: public.ecr.aws/a2c8l1h5/workorder-service-so:${{ github.sha }}"
        echo "Image pushed: public.ecr.aws/a2c8l1h5/workorder-service-so:latest"